# 全局配置参数 说明

FIGHT_SPIRIT_FACTOR = 0.1 # 战意系数
WIN_RATE_FACTOR = 0.6 # 胜率系数
HOME_AWAY_WIN_RATE_FACTOR = 0.2 # 主客场胜率系数
ATTACK_ABILITY_FACTOR = 0.25 # 进攻系数
DEFENCE_ABILITY_FACTOR = 0.25 # 防守系数
GENERAL_ABILITY_FACTOR = 0.5  # 综合系数

# key值